name: cat_trivia
description: ProArea Test Assignment

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  retrofit: '>=3.0.0 <4.0.0'
  skeleton_text: ^3.0.0
  stash_hive: ^4.3.4
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  json_serializable: '>4.4.0'
  hive_generator: ^1.1.3
  retrofit_generator: '>=4.0.0 <5.0.0'

flutter:
  uses-material-design: true